name: Deploy Web Workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist/
          MESSAGE: "{sha} {msg}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
